### PR TITLE
Removed deprecated and useless default value in PHP8.

### LINKED ISSUE #619: image_downsize() PHP8 Required parameter $id follows optional parameter $false
**ErrorException** Deprecated: Required parameter $id follows optional parameter $false 
in /wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php 1320 
(https://github.com/udx/wp-stateless/blob/v3.0/lib/classes/class-bootstrap.php#L1320)

- WP-Stateless: 3.1.1
- PHP: 8.0.9
- WP: 5.8

_Details_:
- file: `../wp-stateless/lib/classes/class-bootstrap.php`
- line: 1320
- message: Required parameter $id follows optional parameter $false

### PR DESCRIPTION
**Pull request by megazalrock**
In PHP 8, E_DEPRECATED will occur if a function has an argument with a default value followed by a required argument.
Also, if the function is executed with apply_filter, it is not necessary to specify a default value.

This PR fixes #619.

### CODE REVIEW

**Review by rolandinsh — APPROVED** [review]

File: lib/classes/class-bootstrap.php [hunk 1]
```diff
@@ -1317,7 +1317,7 @@ public function views_upload($views) {
        * @param string $size
        * @return mixed $false
        */
-      public function image_downsize($false = false, $id, $size) {
+      public function image_downsize($false, $id, $size) {
```
Comment (rolandinsh) [inline lib/classes/class-bootstrap.php:1320]: simple and effective :)

**Review by rolandinsh — APPROVED** [review]

**Review by rolandinsh — APPROVED** [review]

**Review by rolandinsh — APPROVED** [review]

**Comment by planv** [comment]
@megazalrock 

Thank you for this fix. It will be included to the next release.
